- hosts: testservers
  gather_facts: no
  become: yes
  become_user: root

  tasks:
    - name: install the latest version of Apache
      yum: name=httpd state=latest

    - name: enabled httpd auto start
      service:
        name=httpd
        state=started
        enabled=yes

    - name: restart service httpd
      service:
        name=httpd
        state=restarted
        
